trigger:
    - main

variables:
  - template: .\env-variables.yml # 
    
  - name: vmImageName
    value: "windows-latest"
  - name: notebooksPath # Azure databricks folder path, we created a folder called notebook to store only the notebooks
    value: "notebook"

pool:
  vmImage: ${{ variables.vmImageName }}

stages:
  - template: templates/deploy-notebooks.yml # referring to templates folder inside CICD folder
    parameters:
    stageId: "Deploy_to_Dev_Environment" # CI part
    env: "dev"
    environmentName: ${{ variables.dev-environment-name }} #create in pipeline variable group dbw-cicd-dev ("dev-environment-databricks-cicd")
    resourceGroupName: ${{ variables.dev-resource-group-name }} #create in pipeline variable group dbw-cicd-dev and define value
    serviceConnection: ${{ variables.dev-service-connection-name }} #create in pipeline variable group dbw-cicd-dev ("dev-service-connection")
    notebooksPath: ${{ variables.notebooksPath }}
  
  - template: templates/deploy-notebooks.yml # referring to templates folder inside CICD folder
    parameters:
    dependsOn: ["Deploy_to_Dev_Environment"]
    stageId: "Deploy_to_PROD_Environment" # CI part
    env: "prod"
    environmentName: ${{ variables.prod-environment-name }} #create in pipeline variable group dbw-cicd-dev ("prod-environment-databricks-cicd")
    resourceGroupName: ${{ variables.prod-resource-group-name }} #create in pipeline variable group dbw-cicd-dev and define value
    serviceConnection: ${{ variables.prod-service-connection-name }} #create in pipeline variable group dbw-cicd-dev ("prod-service-connection")
    notebooksPath: ${{ variables.notebooksPath }} # stays same because notebook folder source is same