trigger:
    - main

variables:
  - template: .\env-variables.yml
    
  - name: vmImageName
    value: "windows-latest"
  - name: notebooksPath
    value: "notebook"

pool:
  vmImage: ${{ variables.vmImageName }}

stages:
 - stage: DoingDBRickstuff
   jobs:
    - template: templates/deploy-notebooks.yml
      parameters:
        stageId: "Deploy_to_Dev_Environment"
        env: "dev"
        environmentName: ${{ variables['dev-environment-name'] }}
        resourceGroupName: ${{ variables['dev-resource-group-name'] }}
        serviceConnection: ${{ variables['dev-service-connection-name'] }}
        notebooksPath: ${{ variables.notebooksPath }}
    
    - template: templates/deploy-notebooks.yml
      parameters:
        dependsOn: ["Deploy_to_Dev_Environment"]
        stageId: "Deploy_to_PROD_Environment"
        env: "prod"
        environmentName: ${{ variables['prod-environment-name'] }}
        resourceGroupName: ${{ variables['prod-resource-group-name'] }}
        serviceConnection: ${{ variables['prod-service-connection-name'] }}
        notebooksPath: ${{ variables.notebooksPath }}