parameters:
- name: stageId
  type: string
- name: env
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: serviceConnection
  type: string
- name: notebooksPath
  type: string
- name: databricksHost
  type: string
- name: databricksToken
  type: string  

jobs:
- deployment: ${{ parameters.stageId }}
  displayName: "Deploy Databricks Notebooks to ${{ parameters.env }}"
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
            addToPath: true

        - script: |
            python -m pip install --upgrade pip
            pip install databricks-cli
          displayName: 'Install Databricks CLI'

        - script: |
            mkdir -p ~/.databrickscfg
            echo "[DEFAULT]" > ~/.databrickscfg
            echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
            echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
          displayName: 'Configure Databricks CLI'
          env:
            DATABRICKS_HOST: ${{ parameters.databricksHost }}
            DATABRICKS_TOKEN: ${{ parameters.databricksToken }}

        - script: |
            databricks workspace import_dir ${{ parameters.notebooksPath }} /Workspace/TargetPath --overwrite
          displayName: 'Deploy files to Databricks workspace'
          env:
            DATABRICKS_HOST: $(DATABRICKS_HOST)
            DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)