parameters:
- name: stageId
  type: string
- name: dependson
  type: object
  default: []
- name: env
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: serviceConnection
  type: string
- name: notebooksPath
  type: string

jobs:
- deployment: ${{ parameters.stageId }} # Parameterized job name for uniqueness
  displayName: "Deploy Databricks Notebooks to ${{ parameters.env }}"
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        # Install Azure CLI (this is for self-hosted agents)
        # - task: PowerShell@2
        #   displayName: "Install Azure CLI"
        #   inputs:
        #     targetType: 'inline'
        #     script: |
        #       echo "Installing Azure CLI..."
        #       Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
        #       Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /quiet /norestart' -Wait
        #       # Add Azure CLI to PATH for the current process
        #       $env:Path += ";C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin"

        # # Install PowerShell Core
        # - task: PowerShell@2
        #   displayName: "Install PowerShell Core"
        #   inputs:
        #     targetType: 'inline'
        #     script: |
        #       echo "Installing PowerShell Core..."
        #       Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.3.6/PowerShell-7.3.6-win-x64.msi -OutFile .\PowerShell.msi
        #       Start-Process msiexec.exe -ArgumentList '/I PowerShell.msi /quiet /norestart' -Wait

        # Verify installations
        - task: PowerShell@2
          displayName: "Verify Azure CLI and PowerShell Core"
          inputs:
            targetType: 'inline'
            script: |
              az --version
              pwsh -Command '$PSVersionTable'

        - checkout: self
          displayName: "Checkout repository"

        - task: AzureCLI@2
          displayName: "GetToken Copy Notebooks"
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
                # Set Azure CLI to use dynamic installs
                az config set extension.use_dynamic_install=yes_without_prompt
                az config set extension.dynamic_install_allow_preview=true

                # Get Databricks workspace ID
                $databricksWorkspace = (az resource list --resource-group ${{ parameters.resourceGroupName }} --query "[?type=='Microsoft.Databricks/workspaces'].id" --output tsv)

                # Get Databricks workspace details
                $databricksWorkspaceInfo = (az databricks workspace show --ids $databricksWorkspace --output json | ConvertFrom-Json)

                # Get Databricks access token (replace with your logic)
                $bearerToken = & "$(Build.Repository.LocalPath)/dbx-using-cicdtools-azdevops/scripts/DatabricksToken.ps1" -databricksworkspaceResourceId $databricksWorkspaceInfo.id -databricksWorkspaceUrl $databricksWorkspaceInfo.workspaceUrl

                # Install azure.databricks.cicd.tools module
                Install-Module -Name azure.databricks.cicd.tools -Force -Scope CurrentUser

                # Get Git repository path for Notebooks then deploy to Databricks workspace to allocated location
                Import-Module -Name azure.databricks.cicd.tools
                Import-DatabricksFolder -BearerToken $bearerToken -Region $databricksWorkspaceInfo.location -LocalPath "$(Build.Repository.LocalPath)/${{ parameters.notebooksPath }}" -DatabricksPath "/live" -Clean