trigger:
    - main

variables:
  - template: .\env-variables.yml
    
  - name: vmImageName
    value: "windows-latest"
  - name: notebooksPath
    value: "dbx-using-cicdtools/notebooks"

pool:
  vmImage:  $(vmImageName)

stages:
 - stage: DoingDev
   jobs:
    - template: templates/deploy-notebooks.yml
      parameters:
        stageId: "Deploy_to_Dev_Environment"
        env: "dev"
        environmentName: ${{ variables['dev-environment-name'] }}
        resourceGroupName: ${{ variables['dev-resource-group-name'] }}
        serviceConnection: ${{ variables['dev-service-connection-name'] }}
        notebooksPath: $(notebooksPath)

 - stage: DoingProd
   dependsOn: DoingDev  # Ensures PROD runs only after DEV succeeds
   jobs:
    - template: templates/deploy-notebooks.yml
      parameters:
        stageId: "Deploy_to_PROD_Environment"
        env: "prod"
        environmentName: ${{ variables['prod-environment-name'] }}
        resourceGroupName: ${{ variables['prod-resource-group-name'] }}
        serviceConnection: ${{ variables['prod-service-connection-name'] }}
        notebooksPath: $(notebooksPath)
