trigger:
- cgpersonal

variables:
  - name: DATABRICKS_HOST
    value: 'https://adb-1055291633315799.19.azuredatabricks.net' # Replace with your Databricks instance URL
  - group: Dev-vars

parameters:
  - name: notebooksPath
    displayName: 'Path to Notebooks'
    type: string
    default: "dbx-using-cicdtools-azdevops/notebooks"
  - name: serviceConnection
    displayName: 'Azure Service Connection'
    type: string
    default: 'bloom-connect-vse'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli
  displayName: 'Install Databricks CLI'

- task: AzureCLI@2
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      export CLIENT_ID="557fa95a-5c11-4b0c-987a-d38b6633b07b"
      # Use CLIENT_SECRET directly from the variable group
      export CLIENT_SECRET=$DATABRICKS_CLIENT_SECRET

      response=$(curl --silent --request POST \
      --url https://adb-1055291633315799.19.azuredatabricks.net//oidc/v1/token \
      --user "$CLIENT_ID:$CLIENT_SECRET" \
      --data 'grant_type=client_credentials&scope=all-apis')
      DATABRICKS_TOKEN=$(echo $response | jq -r '.access_token')
      DATABRICKS_HOST=$(DATABRICKS_HOST)
      echo -e "[DEFAULT]\nhost = $DATABRICKS_HOST\ntoken = $DATABRICKS_TOKEN" > ~/.databrickscfg
      databricks workspace ls
  env:
    DATABRICKS_HOST: https://adb-1055291633315799.19.azuredatabricks.net
    DATABRICKS_CLIENT_SECRET: $(databrickstoken-appreg-srvcondevops-dev) # Reference the secret from the variable group
    DATABRICKS_CLIENT_ID: 557fa95a-5c11-4b0c-987a-d38b6633b07b
  displayName: 'Authenticate with Azure CLI and Configure Databricks CLI'
#$(az account get-access-token --resource=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --query accessToken -o tsv)


- script: |
    databricks workspace import_dir $(Build.SourcesDirectory)/${{ parameters.notebooksPath }} /live --overwrite
  env:
    DATABRICKS_CONFIG_FILE: ~/.databrickscfg
  displayName: 'Upload Notebooks to Databricks Workspace'