trigger:
- cgpersonal

variables:
  - name: DATABRICKS_HOST
    value: 'https://adb-1055291633315799.19.azuredatabricks.net' # Replace with your Databricks instance URL
  - group: Dev-vars

parameters:
  - name: notebooksPath
    displayName: 'Path to Notebooks'
    type: string
    default: "dbx-using-cicdtools-azdevops/notebooks"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli

- script: |
    databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_CLIENT_SECRET
  env:
    DATABRICKS_HOST: https://adb-1055291633315799.19.azuredatabricks.net
    DATABRICKS_CLIENT_SECRET: $(databrickstoken-appreg-srvcondevops-dev)
  displayName: 'Configure Databricks CLI'

- script: |
    databricks workspace import_dir $(Build.SourcesDirectory)/${{ parameters.notebooksPath }} /live --overwrite
  env:
    DATABRICKS_HOST: https://adb-1055291633315799.19.azuredatabricks.net
    DATABRICKS_CLIENT_ID: 557fa95a-5c11-4b0c-987a-d38b6633b07b
    DATABRICKS_CLIENT_SECRET: $(databrickstoken-appreg-srvcondevops-dev)
  displayName: 'Upload Notebooks to Databricks Workspace'