trigger:
- cgpersonal

variables:
  - name: DATABRICKS_HOST
    value: 'https://adb-1055291633315799.19.azuredatabricks.net' # Replace with your Databricks instance URL
  - group: Dev-vars

parameters:
  - name: notebooksPath
    displayName: 'Path to Notebooks'
    type: string
    default: "dbx-using-cicdtools-azdevops/notebooks"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli
    mkdir -p ~/.databricks
    echo "[DEFAULT]" > ~/.databricks/config
    echo "host = $(DATABRICKS_HOST)" >> ~/.databricks/config
    echo "token = $(databrickstoken-appreg-srvcondevops-dev)" >> ~/.databricks/config
  displayName: 'Install and Configure Databricks CLI'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(databrickstoken-appreg-srvcondevops-dev)

- script: |
    export DATABRICKS_HOST=$(DATABRICKS_HOST)
    export DATABRICKS_TOKEN=$(databrickstoken-appreg-srvcondevops-dev)
    databricks workspace import_dir $(Build.SourcesDirectory)/${{ parameters.notebooksPath }} /live --overwrite
  displayName: 'Run Databricks Import Command'
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(databrickstoken-appreg-srvcondevops-dev)