trigger:
- cgpersonal

variables:
  - name: DATABRICKS_HOST
    value: 'https://adb-1055291633315799.19.azuredatabricks.net' # Replace with your Databricks instance URL
  - group: Dev-vars

parameters:
  - name: notebooksPath
    displayName: 'Path to Notebooks'
    type: string
    default: "dbx-using-cicdtools-azdevops/notebooks"
  - name: serviceConnection
    displayName: 'Azure Service Connection'
    type: string
    default: 'bloom-connect-vse'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli
  displayName: 'Install Databricks CLI'


- task: AzureCLI@2
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      export DATABRICKS_HOST=$DATABRICKS_HOST
      export DATABRICKS_ACCOUNT_ID=$DATABRICKS_ACCOUNT_ID
      export DATABRICKS_CLIENT_ID=$DATABRICKS_CLIENT_ID
      export DATABRICKS_CLIENT_SECRET=$DATABRICKS_CLIENT_SECRET

      response=$(curl --silent --request POST \
      --url https://accounts.azuredatabricks.net/oidc/accounts/$DATABRICKS_ACCOUNT_ID/v1/token \
      --user "$DATABRICKS_CLIENT_ID:$DATABRICKS_CLIENT_SECRET" \
      --data 'grant_type=client_credentials&scope=all-apis')
      DATABRICKS_TOKEN=$(echo $response | jq -r '.access_token')
      DATABRICKS_HOST=$(DATABRICKS_HOST)
      echo -e "[DEFAULT]\nhost = $DATABRICKS_HOST\ntoken = $DATABRICKS_TOKEN" > ~/.databrickscfg
      
  env:
    DATABRICKS_HOST: https://adb-1055291633315799.19.azuredatabricks.net
    DATABRICKS_CLIENT_SECRET: $(databrickstoken-appreg-srvcondevops-dev) # Reference the secret from the variable group
    DATABRICKS_CLIENT_ID: 557fa95a-5c11-4b0c-987a-d38b6633b07b
    DATABRICKS_ACCOUNT_ID: 6f11c974-e6ce-45aa-9df3-cb8d50d74416
  displayName: 'Authenticate with Azure CLI and Configure Databricks CLI'

- script: |
    databricks workspace ls
    databricks workspace import_dir $(Build.SourcesDirectory)/${{ parameters.notebooksPath }} /live3 --overwrite
  displayName: 'Write out notebooks to Workspace'

