name: Deploy Databricks Secret Scope

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install New Databricks CLI (v0.200+)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install databricks-cli==0.205.0  # Use a version that supports `auth login`
      

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: "3be2ce56-4a5f-4034-88d7-2953d1819ed3"
      
      - name: Configure Databricks CLI with AAD auth
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: "3be2ce56-4a5f-4034-88d7-2953d1819ed3"
        run: |
          # Login to Azure using az CLI
          az login --service-principal \
            --username $ARM_CLIENT_ID \
            --tenant $ARM_TENANT_ID \
            --password ${{ secrets.AZURE_CLIENT_SECRET }}
        
          # Set environment variables needed by databricks auth login
          export DATABRICKS_AZURE_RESOURCE_ID="/subscriptions/3be2ce56-4a5f-4034-88d7-2953d1819ed3/resourceGroups/commonResources/providers/Microsoft.Databricks/workspaces/YOUR_WORKSPACE_NAME"
          export DATABRICKS_HOST="https://adb-1432846341870043.3.azuredatabricks.net"
        
          # Authenticate using AAD and set the profile
          databricks auth login --azure-login --host $DATABRICKS_HOST
        
      # - name: Configure Databricks CLI
      #   env:
      #     DATABRICKS_HOST: https://adb-1432846341870043.3.azuredatabricks.net
      #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
        
      #   run: |
      #       databricks configure --token <<EOF
      #       $DATABRICKS_HOST
      #       $DATABRICKS_TOKEN
      #       EOF

      - name: Create Key Vault-Backed Secret Scope
        run: |
          databricks secrets create-scope --scope dbxsecrets1 \
            --scope-backend-type AZURE_KEYVAULT \
            --resource-id /subscriptions/3be2ce56-4a5f-4034-88d7-2953d1819ed3/resourceGroups/commonResources/providers/Microsoft.KeyVault/vaults/keyvault-forgeneraluse \
            --dns-name https://keyvault-forgeneraluse.vault.azure.net \
            --initial-manage-principal users

