name: Deploy Databricks Secret Scope

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --host https://adb-1432846341870043.3.azuredatabricks.net/ --token ${{ secrets.DATABRICKS_TOKEN_DEV }}

      - name: Create Key Vault-Backed Secret Scope
        run: |
          databricks secrets create-scope --scope dbxsecrets1 \
            --scope-backend-type AZURE_KEYVAULT \
            --resource-id /subscriptions/3be2ce56-4a5f-4034-88d7-2953d1819ed3/resourceGroups/commonResources/providers/Microsoft.KeyVault/vaults/keyvault-forgeneraluse \
            --dns-name https://keyvault-forgeneraluse.vault.azure.net/
