name: db1

on:
  workflow_call:
    inputs:
      stageId:
        required: true
        type: string
      env:
        required: true
        type: string
      environmentName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      serviceConnection:
        required: true
        type: string
      notebooksPath:
        required: true
        type: string

jobs:
  deploy-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Configure Azure CLI
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az config set extension.dynamic_install_allow_preview=true

      - name: Deploy Databricks Notebooks
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          echo "Deploying notebooks to ${env} environment"
          echo "Using resource group: ${resourceGroupName}"
          echo "Notebooks path: ${notebooksPath}"

          # Deploy the notebooks using Databricks CLI or API
          az databricks workspace import_dir \
            --profile ${env} \
            --source ${notebooksPath} \
            --destination /Workspace/Users/${env}

          echo "Deployment complete."
