name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Azure CLI
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az config set extension.dynamic_install_allow_preview=true

    # Call the reusable workflow for deploying notebooks
    uses: ./.github/workflows/deploy-notebooks-ghactions.yml
    with:
      stageId: "Deploy_to_Dev_Environment"
      env: "dev"
      environmentName: "dev"
      resourceGroupName: "dbr-analytics-dev"
      serviceConnection: "clintazrealallrgs"
      notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Azure CLI
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az config set extension.dynamic_install_allow_preview=true

    # Call the reusable workflow for deploying notebooks to Prod
    uses: ./.github/workflows/deploy-notebooks-ghactions.yml
    with:
      stageId: "Deploy_to_Prod_Environment"
      env: "prod"
      environmentName: "prod"
      resourceGroupName: "dbr-analytics-prod"
      serviceConnection: ${{ secrets.AZURE_SERVICE_CONNECTION }}
      notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"
