name: "db1-main"

on:
  push:
    branches:
      - getgithubtowork
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

jobs:
  db1:
    uses: ./.github/workflows/deploy-notebooks.yml
    with:
      stageId: "Deploy_to_Dev_Environment"
      dbx-env: dev
      resourceGroupName: "dbr-analytics-dev"
      serviceConnection: "clintazrealallrgs"
      notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"

  deploy-prod:
    uses: ./.github/workflows/deploy-notebooks.yml
    with:
      stageId: "Deploy_to_Prod_Environment"
      dbx-env: prod
      resourceGroupName: "dbr-analytics-prod"
      serviceConnection: "clintazrealallrgs"
      notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"
