name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - getgithubtowork
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Notebooks to Dev
        uses: ./.github/workflows/deploy-notebooks.yml
        with:
          stageId: "Deploy_to_Dev_Environment"
          env: "dev"
          environmentName: "dev"
          resourceGroupName: "dbr-analytics-dev"
          serviceConnection: "clintazrealallrgs"
          notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"

  # deploy-prod:
  #   steps:
  #     - name: Deploy Notebooks to Prod
  #       uses: ./.github/workflows/deploy-notebooks.yml
  #       with:
  #         stageId: "Deploy_to_Prod_Environment"
  #         env: "prod"
  #         environmentName: "prod"
  #         resourceGroupName: "dbr-analytics-prod"
  #         serviceConnection: ${{ secrets.AZURE_SERVICE_CONNECTION }}
  #         notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"
  #     serviceConnection: ${{ secrets.AZURE_SERVICE_CONNECTION }}
  #     notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"
