name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - getgithubtowork
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Call reusable workflow for deploying notebooks to Dev
      uses: ./.github/workflows/deploy-notebooks.yml
      with:
        stageId: "Deploy_to_Dev_Environment"
        env: "dev"
        environmentName: "dev"
        resourceGroupName: "dbr-analytics-dev"
        serviceConnection: "clintazrealallrgs"
        notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Call reusable workflow for deploying notebooks to Prod
      uses: ./.github/workflows/deploy-notebooks.yml
      with:
        stageId: "Deploy_to_Prod_Environment"
        env: "prod"
        environmentName: "prod"
        resourceGroupName: "dbr-analytics-prod"
        serviceConnection: ${{ secrets.AZURE_SERVICE_CONNECTION }}
        notebooksPath: "dbx-using-cicdtools-githubactions/notebooks"
